version: "3.8"
services:
  mariadb: &mariadb
    image: arm64v8/mariadb
    command:
      --character-set-server=utf8
      --collation-server=utf8_unicode_ci
      --connect-timeout=10
      --max-connections=3000
      --max-allowed-packet=32M
      --thread-cache-size=300
      --sort-buffer-size=4M
      --bulk-insert-buffer-size=16M
      --tmp-table-size=256M
      --max-heap-table-size=2048M
      --query-cache-size=64M
      --query-cache-type=0
      --long-query-time=10
      --expire-logs-days=10
      --max-binlog-size=100M
      --key-buffer-size=1024M
      --innodb-buffer-pool-size=256M
      --innodb-log-buffer-size=32M
      --innodb-file-per-table=1
      --innodb-open-files=400
      --innodb-io-capacity=400
      --innodb-flush-method=O_DIRECT
      #--sql-mode="STRICT_TRANS_TABLES,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION"
  gridbot-db:
    <<: *mariadb
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
    env_file:
      - .env
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}

  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - gridbot-db
    links:
      - gridbot-db
    environment:
      PMA_HOSTS: gridbot-db
      PMA_ABSOLUTE_URI: ${PMA_ABSOLUTE_URI}

  app:
    container_name: app
    build: .
    restart: always
    command: bash -c "uvicorn main:app --host 0.0.0.0 --port 8000 --reload" # production mode
    # command: bash -c "/app/bootstrap.sh" # debug mode
    # command: bash -c "/app/bootstrap.sh" # then `docker exec -it app /bin/bash` to run uvicon, easier to debug
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - gridbot-db